# explanation (solution provided by [geeks for geeks](https://www.geeksforgeeks.org/converting-matrix-into-row-echelon-form-in-python/) )

initial matrix

$$
\begin{bmatrix}

 2  & -2 & 4  & -2 \\
 2  &  1 & 10 &  7 \\
-4  &  4 & -8 &  4 \\
 4  & -1 & 14 &  6 \\
 
\end{bmatrix}
$$

we use Gaussian Elimination to achieve the desired row-echelon form

we have a pivot row for every iteration starting with row "0" 

first we locate the first non zero row for the current column

our current column is 0 so we look for the first row with a non zero element on col[0]

in this case it's the first row

so the pivot row and mathces with the non zero row

we swap them (in this case nothing happens)

$$
\begin{bmatrix}

 2  & -2 & 4  & -2 \\

\end{bmatrix}
$$

we now take the element at [0,0] and we devide everything with it keeping only the remainder using the // operator

so we take 2 and perform the division

the first row becomes:

$$
\begin{bmatrix}

 1 & -1 & 2  & -1 \\

\end{bmatrix}
$$


Now we take the row try to eliminate all of the elements in the current column in the rows bellow, in this case:

for row 1:

$$
\begin{bmatrix}
 2  &  1 & 10 &  7 \\
\end{bmatrix}
- 
\begin{bmatrix}
 2  & -2 & 4  & -2 \\
\end{bmatrix}
=
\begin{bmatrix}
 0  & 3 & 6  & 9 \\
\end{bmatrix}

$$

row 2

$$
\begin{bmatrix}
-4  &  4 & -8 &  4 \\
\end{bmatrix}
+ 2 * 
\begin{bmatrix}
 2  & -2 & 4  & -2 \\
\end{bmatrix}
=
\begin{bmatrix}
 0  & 0 & 0  & 0 \\
\end{bmatrix}

$$

row 3

$$
\begin{bmatrix}
 4  & -1 & 14 &  6 \\
\end{bmatrix}
- 2 * 
\begin{bmatrix}
 2  & -2 & 4  & -2 \\
\end{bmatrix}
=
\begin{bmatrix}
 0  & 3 & 6  & 10 \\
\end{bmatrix}

$$


thus we get:

$$
\begin{bmatrix}

 1  & -1 & 2 & -1 \\
 0  &  3 & 6 &  9 \\
 0  &  0 & 0 &  0 \\
 0  &  3 & 6 & 10 \\
 
\end{bmatrix}
$$




In [39]:
import numpy as np
# Function to check if matrix is in REF

def is_row_echelon_form(matrix):
	if not matrix.any():
		return False

	rows = matrix.shape[0]
	cols = matrix.shape[1]
	prev_leading_col = -1

	for row in range(rows):
		leading_col_found = False
		for col in range(cols):
			if matrix[row, col] != 0:
				if col <= prev_leading_col:
					return False
				prev_leading_col = col
				leading_col_found = True
				break
		if not leading_col_found and any(matrix[row, col] != 0 for col in range(cols)):
			return False
	return True

def find_nonzero_row(matrix, pivot_row, col):
	nrows = matrix.shape[0]
	for row in range(pivot_row, nrows):
		if matrix[row, col] != 0:
			return row
	return None

# Swapping rows so that we can have our non zero row on the top of the matrix
def swap_rows(matrix, row1, row2):
	matrix[[row1, row2]] = matrix[[row2, row1]]

def make_pivot_one(matrix, pivot_row, col):
	pivot_element = matrix[pivot_row, col]
	matrix[pivot_row] //= pivot_element
	# print(pivot_element)

def eliminate_below(matrix, pivot_row, col):
	nrows = matrix.shape[0]
	pivot_element = matrix[pivot_row, col]
	for row in range(pivot_row + 1, nrows):
		factor = matrix[row, col]
		matrix[row] -= factor * matrix[pivot_row]

# Implementing above functions
def row_echelon_form(matrix):
	nrows = matrix.shape[0]
	ncols = matrix.shape[1]
	pivot_row = 0
# this will run for number of column times. If matrix has 3 columns this loop will run for 3 times
	for col in range(ncols):
		nonzero_row = find_nonzero_row(matrix, pivot_row, col)
		# print(nonzero_row)
		print("before \n", matrix)
		if nonzero_row is not None:
			swap_rows(matrix, pivot_row, nonzero_row)
			print("after \n", matrix)
			make_pivot_one(matrix, pivot_row, col)
			eliminate_below(matrix, pivot_row, col)

			# print(matrix)
			pivot_row += 1
			
	return matrix


matrix = np.array([[2,-2,4,-2],[2,1,10,7],[-4,4,-8,4],[4,-1,14,6]])
print("Matrix Before Converting:")
print(matrix)
print()
result = row_echelon_form(matrix)
print("After Converting to Row Echelon Form:")
print(result)
if is_row_echelon_form(result):
	print("In REF")
else:
	print("Not in REF--------------->")


Matrix Before Converting:
[[ 2 -2  4 -2]
 [ 2  1 10  7]
 [-4  4 -8  4]
 [ 4 -1 14  6]]

before 
 [[ 2 -2  4 -2]
 [ 2  1 10  7]
 [-4  4 -8  4]
 [ 4 -1 14  6]]
after 
 [[ 2 -2  4 -2]
 [ 2  1 10  7]
 [-4  4 -8  4]
 [ 4 -1 14  6]]
before 
 [[ 1 -1  2 -1]
 [ 0  3  6  9]
 [ 0  0  0  0]
 [ 0  3  6 10]]
after 
 [[ 1 -1  2 -1]
 [ 0  3  6  9]
 [ 0  0  0  0]
 [ 0  3  6 10]]
before 
 [[ 1 -1  2 -1]
 [ 0  1  2  3]
 [ 0  0  0  0]
 [ 0  0  0  1]]
before 
 [[ 1 -1  2 -1]
 [ 0  1  2  3]
 [ 0  0  0  0]
 [ 0  0  0  1]]
after 
 [[ 1 -1  2 -1]
 [ 0  1  2  3]
 [ 0  0  0  1]
 [ 0  0  0  0]]
After Converting to Row Echelon Form:
[[ 1 -1  2 -1]
 [ 0  1  2  3]
 [ 0  0  0  1]
 [ 0  0  0  0]]
In REF


# rewrite with no external modules used

In [75]:
"""
    I ASSUME THAT I AM GIVEN A MATRIX THAT HAS EQUAL COLUMNS ON ALL ROWS
"""
def is_row_echelon_form(matrix):

	rows = len(matrix)
	cols = len(matrix[0])
	prev_leading_col = -1

	for row in range(rows):
		leading_col_found = False
		for col in range(cols):
			if matrix[row][col] != 0:
				if col <= prev_leading_col:
					return False
				prev_leading_col = col
				leading_col_found = True
				break
		if not leading_col_found:
			found = False
			for col in range(cols):
				if (matrix[row][col] != 0):
					return False
	return True

def find_nonzero_row(matrix, pivot_row, col):
	nrows = len(matrix)
	for row in range(pivot_row, nrows):
		if matrix[row][col] != 0:
			return row
	return None

# Swapping rows so that we can have our non zero row on the top of the matrix
def swap_rows(matrix, row1, row2):
	r1_temp = matrix[row1]
	r2_temp = matrix[row2]
	# matrix[row1, row2] = matrix[row2, row1]
	matrix[row1] = r2_temp
	matrix[row2] = r1_temp

def make_pivot_one(matrix, pivot_row, col):
	pivot_element = matrix[pivot_row][col]
	for i in range(len(matrix[pivot_row])):
		matrix[pivot_row][i] //= pivot_element
	# print(pivot_element)

def eliminate_below(matrix, pivot_row, col):
	nrows = len(matrix)
	pivot_element = matrix[pivot_row][col]
	
	for row in range(pivot_row + 1, nrows):
	
	
	
		factor = matrix[row][col]
		for i in range(len(matrix[row])):
			matrix[row][i] -= factor * matrix[pivot_row][i]

# Implementing above functions
def row_echelon_form(matrix):
	nrows = len(matrix)
	ncols = len(matrix[0])
	pivot_row = 0
# this will run for number of column times. If matrix has 3 columns this loop will run for 3 times
	for col in range(ncols):
		nonzero_row = find_nonzero_row(matrix, pivot_row, col)
		print(nonzero_row)	
		if nonzero_row is not None:
			swap_rows(matrix, pivot_row, nonzero_row)
			
			make_pivot_one(matrix, pivot_row, col)
			eliminate_below(matrix, pivot_row, col)

		# 	print(matrix)
			pivot_row += 1
			
	return matrix


In [74]:
matrix = [
    [2,-2,4,-2],
    [2,1,10,7],
    [-4,4,-8,4],
    [4,-1,14,6]
]

result =  row_echelon_form(matrix)


if is_row_echelon_form(result):
	print("In REF")
else:
	print("Not in REF--------------->")


0
1
None
3
In REF
