In [3]:
from sklearn.linear_model import Ridge
import numpy as np

def ridge_regression_demo(x, y, alpha=1.0):
    """
    Performs ridge regression on the provided data points and returns the coefficients.
    
    Parameters:
    - x: array-like, shape (n_samples,) - The input values of the data points.
    - y: array-like, shape (n_samples,) - The output/target values of the data points.
    - alpha: float - Regularization strength; must be a positive float. Larger values specify stronger regularization.
    
    Returns:
    - coef_: array - Coefficients of the model.
    - intercept_: float - Intercept of the model.
    """
    # Reshape x to (-1, 1) because sklearn expects it in this shape
    x_reshaped = x.reshape(-1, 1)
    
    # Create and fit the model
    model = Ridge(alpha=alpha)
    model.fit(x_reshaped, y)
    
    # Return the coefficient and intercept
    return model.coef_[0], model.intercept_

# Example usage
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 3, 4, 5, 6])

a, b = ridge_regression_demo(x, y, alpha=1.0)
print(f"Line coefficients: a = {a}, b = {b}")


Line coefficients: a = 0.9090909090909092, b = 1.2727272727272725


In [3]:
import numpy as np

def ridge_regression(X, y, alpha=1.0):
    """
    Perform ridge regression using the normal equation.

    Parameters:
    - X: numpy array, shape (n_samples, n_features) - Input features.
    - y: numpy array, shape (n_samples,) - Target values.
    - alpha: float - Regularization strength.

    X = [1, x1], [1,x2]

    Returns:
    - coefficients: numpy array - Coefficients for the regression model.
    """
    n_features = X.shape[1]
    X_with_intercept = np.hstack([np.ones((X.shape[0], 1)), X])  
    
    print(X_with_intercept)

    I = np.eye(n_features + 1)
    I[0, 0] = 0  
    
    coefficients = np.linalg.inv(X_with_intercept.T.dot(X_with_intercept) + alpha * I).dot(X_with_intercept.T).dot(y)
    
    return coefficients  

# Example usage
X = np.array([[1], [2], [3], [4], [5]])  

print(X)
y = np.array([2, 3, 4, 5, 6])

coefficients = ridge_regression(X, y, alpha=1.0)

a, b = ridge_regression(X, y , alpha=1.0)
print(f"Coefficients: {coefficients}")

print("a = ", a, " b = ", b)


[[1]
 [2]
 [3]
 [4]
 [5]]
[[1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]]
[[1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]]
Coefficients: [1.27272727 0.90909091]
a =  1.2727272727272743  b =  0.909090909090909
